name: Deploy Pages

on:
  push:
    branches: ["main"]


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
      # 1. Checkout con LFS habilitado
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      # 1.1 Asegurar que los archivos LFS se descarguen realmente
      - name: Checkout LFS objects
        run: git lfs checkout

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3.1 Configurar Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 3. Instalar dependencias (solo si existe requirements.txt)
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # 4. Validar estructura
      - name: Validate structure
        run: python scripts/validate_structure.py

      # 5. Vincular y Generar sitio
      - name: Link and Generate site
        run: |
          python scripts/link_assets_to_content.py
          python scripts/generate_site.py

      # 6. Crear archivo .nojekyll (evita que GitHub use Jekyll)
      - name: Disable Jekyll
        run: touch site/.nojekyll

      # 7. Subir artefacto
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site

      # 8. Deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
